stages:
  - pre-build
  - build


.docker-build-tmpl: &docker-build-tmpl
  stage: build
  image: ${CI_REGISTRY_IMAGE}/docker-builder:latest
  services:
    - docker:dind
  script:
    - git fetch --tags
#    - docker login -u "${CI_REGISTRY_USER?}" -p "${CI_REGISTRY_PASSWORD?}" "${CI_REGISTRY?}"
#    - ./build-docker.sh "${ARCHITECTURE}" "${CI_REGISTRY_IMAGE}" --push
    - VERSION="$(git describe --tags --always)"
    - VERSION="${VERSION%-*-*}"
    - RELEASE=$(jq -r .release < etc/ncp.cfg)
    - docker login -u "${CI_REGISTRY_USER?}" -p "${CI_REGISTRY_PASSWORD?}" "${CI_REGISTRY?}"
    - >
      DOCKER_BUILDKIT=1 docker build --progress=plain . -f docker/debian-ncp/Dockerfile --pull
      --build-arg release=${RELEASE?} --build-arg arch=${ARCH?} --build-arg arch_qemu=${ARCH_QEMU?}
      -t "${CI_REGISTRY_IMAGE?}/debian-ncp-${NCP_TAG?}:latest"
      -t "${CI_REGISTRY_IMAGE?}/debian-ncp-${NCP_TAG?}:${CI_PIPELINE_IID}"
      -t "${CI_REGISTRY_IMAGE?}/debian-ncp-${NCP_TAG?}:${VERSION?}"
    - >
      DOCKER_BUILDKIT=1 docker build --progress=plain . -f docker/lamp/Dockerfile
      --build-arg release=${RELEASE?} --build-arg arch=${NCP_TAG?}
      -t "${CI_REGISTRY_IMAGE?}/lamp-${NCP_TAG?}:latest"
      -t "${CI_REGISTRY_IMAGE?}/lamp-${NCP_TAG?}:${CI_PIPELINE_IID}"
      -t "${CI_REGISTRY_IMAGE?}/lamp-${NCP_TAG?}:${VERSION?}"
    - >
      DOCKER_BUILDKIT=1 docker build --progress=plain . -f docker/nextcloud/Dockerfile
      --build-arg release=${RELEASE?} --build-arg arch=${NCP_TAG?}
      -t "${CI_REGISTRY_IMAGE?}/nextcloud-${NCP_TAG?}:latest"
      -t "${CI_REGISTRY_IMAGE?}/nextcloud-${NCP_TAG}:${CI_PIPELINE_IID}"
      -t "${CI_REGISTRY_IMAGE}/nextcloud-${NCP_TAG?}:${VERSION?}"
    - >
      DOCKER_BUILDKIT=1 docker build --progress=plain . -f docker/nextcloudpi/Dockerfile
      --build-arg release=${RELEASE?} --build-arg arch=${NCP_TAG?} --build-arg ncp_ver=${VERSION?}
      -t "${CI_REGISTRY_IMAGE}/nextcloudpi-${NCP_TAG?}:latest"
      -t "${CI_REGISTRY_IMAGE}/nextcloudpi-${NCP_TAG?}:${CI_PIPELINE_IID}"
      -t "${CI_REGISTRY_IMAGE}/nextcloudpi-${NCP_TAG?}:${VERSION?}"

docker-build-amd64:
  << : *docker-build-tmpl
  variables:
    ARCHITECTURE: "x86"

docker-build-armhf:
  <<: *docker-build-tmpl
  variables:
    ARCHITECTURE: "armhf"

docker-build-arm64:
  <<: *docker-build-tmpl
  variables:
    ARCHITECTURE: "arm64"

docker-build-docker-builder:
  stage: pre-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/docker-builder:latest || echo "docker-builder:latest not found in \"${CI_REGISTRY_IMAGE}\"!"
    - docker pull docker:latest
    - |
      if [[ "$(docker inspect -f '{{ .DockerVersion }}' ${CI_REGISTRY_IMAGE}/docker-builder:latest)" != "$(docker inspect -f '{{ .DockerVersion }}' docker:latest)" ]]
      then
        docker build --progress=plain . -f ci/images/docker-builder/Dockerfile -t "${CI_REGISTRY_IMAGE}/docker-builder:latest"
        docker login -u "${CI_REGISTRY_USER?}" -p "${CI_REGISTRY_PASSWORD?}" "${CI_REGISTRY?}"
        docker push "${CI_REGISTRY_IMAGE}/docker-builder:latest"
      fi
